### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nhCoder** [RevEngine3r/river_player#13]
Erro while playing some formats of m3u8, the same video plays through _video_player_ package
**example ur**l:https://tmstr.vidsrc.stream/stream/H4sIAAAAAAAAAw3M0XaCIBgA4FdCYBW7W4mSdehwQEzukN9yoa7tOLOefvse4FtvCA5h017oJWxYw9bJJdAkMLRqEvTWkPcj6T7htt073HWQFuqU2qVB_KnGK63K_lRHRdod28nz1.zLSGFYask7KrPsx50z0WA71EOhgZezjUkKODEBu1cghfZ9fPmxy47EbaucDSAkPxD3rfvyYXg3lWmgVZ8d1A1UJQLR4jprAhqESwzZUyc4djnb2ySbDLfYjVJ4zpGL2VTyZXVAgBxRi4qT__8fJmdSjgWqUaR2x5QnHwsIoCaH39YUKtj73Ud4VqLQmvedxDD_AZIsYfAhAQAA/master.m3u8

**Codec info:** H264 - MPEG-4 AVC

`Playback error
E/ExoPlayerImplInternal(20821):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
E/ExoPlayerImplInternal(20821):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(20821):       at android.os.Looper.loopOnce(Looper.java:230)
E/ExoPlayerImplInternal(20821):       at android.os.Looper.loop(Looper.java:319)
E/ExoPlayerImplInternal(20821):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(20821):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
E/ExoPlayerImplInternal(20821):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(20821):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ExoPlayerImplInternal(20821):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ExoPlayerImplInternal(20821):       at java.lang.Thread.run(Thread.java:1012)
E/flutter (20821): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, , null)
E/flutter (20821): 
`

**Comment by nhCoder** [comment]
My bad adding, just adding a user gent header fixed my problem.
